/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.13 and DSP System Toolbox 9.15.
 * Generated on: 05-Apr-2023 12:19:21
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 31
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 * Arithmetic        : fixed
 * Numerator         : s8,8 -> [-5.000000e-01 5.000000e-01)
 * Input             : s12,12 -> [-5.000000e-01 5.000000e-01)
 * Filter Internals  : Full Precision
 *   Output          : s21,20 -> [-1 1)  (auto determined)
 *   Product         : s19,20 -> [-2.500000e-01 2.500000e-01)  (auto determined)
 *   Accumulator     : s21,20 -> [-1 1)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2022b\extern\include\tmwtypes.h 
 */
const int BL = 31;
const int8_T B[31] = {
      4,    5,    1,   -5,   -7,   -3,    5,   10,    6,   -5,  -15,  -14,
      5,   36,   65,   77,   65,   36,    5,  -14,  -15,   -5,    6,   10,
      5,   -3,   -7,   -5,    1,    5,    4
};
