/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.13 and Signal Processing Toolbox 9.1.
 * Generated on: 13-Apr-2023 12:37:56
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 2
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2022b\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 5
const int NL[MWSPT_NSEC] = { 1,3,1,3,1 };
const real64_T NUM[MWSPT_NSEC][3] = {
  {
     0.9247292607125,                 0,                 0 
  },
  {
                   1,                -2,                 1 
  },
  {
     0.6508410896677,                 0,                 0 
  },
  {
                   1,                -2,                 1 
  },
  {
     0.8912509381337,                 0,                 0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1 };
const real64_T DEN[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.791170018397,   0.9077470244527 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.156831991754,   0.4465323669166 
  },
  {
                   1,                 0,                 0 
  }
};
