/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.13 and DSP System Toolbox 9.15.
 * Generated on: 05-Apr-2023 12:21:55
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 2
 * Stable              : Yes
 * Linear Phase        : No
 * Arithmetic          : single
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2022b\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 5
const int NL[MWSPT_NSEC] = { 1,3,1,3,1 };
const real32_T NUM[MWSPT_NSEC][3] = {
  {
     0.9471681714,              0,              0 
  },
  {
                1,    0.817954123,              1 
  },
  {
     0.9471681714,              0,              0 
  },
  {
                1,    0.817954123,              1 
  },
  {
     0.8912509084,              0,              0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1 };
const real32_T DEN[MWSPT_NSEC][3] = {
  {
                1,              0,              0 
  },
  {
                1,   0.6228883862,   0.8976661563 
  },
  {
                1,              0,              0 
  },
  {
                1,   0.9215223193,   0.9048275948 
  },
  {
                1,              0,              0 
  }
};
