/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.13 and Signal Processing Toolbox 9.1.
 * Generated on: 12-Apr-2023 16:43:10
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 2
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2022b\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 5
const int NL[MWSPT_NSEC] = { 1,3,1,3,1 };
const real64_T NUM[MWSPT_NSEC][3] = {
  {
     0.9947779582413,                 0,                 0 
  },
  {
                   1,   0.9818613433107,                 1 
  },
  {
     0.9947779582413,                 0,                 0 
  },
  {
                   1,   0.9818613433107,                 1 
  },
  {
     0.8912509381337,                 0,                 0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1 };
const real64_T DEN[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,   0.9619369925488,   0.9895783969535 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,    0.991461175742,   0.9896772701768 
  },
  {
                   1,                 0,                 0 
  }
};
